#!/bin/bash
CGLOBS=/tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing git..."
cd $CPKG
if [[ "$ARCH" == "i686" ]];then
    installer "https://dl.bintray.com/chromebrew/chromebrew/git-2.16.1-chromeos-i686.tar.xz" $CPKG/git.tar.xz
elif [[ "$ARCH" == "x86_64" ]];then 
	installer "https://dl.bintray.com/chromebrew/chromebrew/git-2.16.1-chromeos-x86_64.tar.xz" $CPKG/git.tar.xz
fi
unpacker "git.tar.xz" $CBUILD

cd $CBUILD
sudo cp -r usr/local/ /usr/  # Move all of the files
cleaner $CBUILD # Clean up files
echo "Done"
