#!/bin/bash
CGLOBS=/tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
NODE_BUILD=$CBUILD/nodebrew-0.9.8
NODE_VERSION="v9.7.1"

echo "
Installing node..."
cd $CPKG
installer "https://github.com/hokaccha/nodebrew/archive/v0.9.8.tar.gz" $CPKG/node.tar.gz
unpacker "node.tar.gz" $CBUILD
cd $NODE_BUILD
sudo mkdir -p $PREF/share/nodebrew
NODEBREW_ROOT=$PREF/share/nodebrew sudo perl nodebrew setup > /dev/null
[ -L $BIN_DIR/nodebrew ] && sudo rm $BIN_DIR/nodebrew
[ -L $BIN_DIR/node ] && sudo rm $BIN_DIR/node
[ -L $BIN_DIR/npm ] && sudo rm $BIN_DIR/npm
[ -L $BIN_DIR/npx ] && sudo rm $BIN_DIR/npx
[ -L $HOME/.nodebrew ] && sudo rm -rf $HOME/.nodebrew
sudo ln -s $PREF/share/nodebrew $HOME/.nodebrew
sudo ln -s $PREF/share/nodebrew/nodebrew $BIN_DIR/nodebrew
sudo nodebrew install-binary "$NODE_VERSION"

sudo ln -s "$PREF/share/nodebrew/node/$NODE_VERSION/bin/node $BIN_DIR/node"
sudo ln -s "$PREF/share/nodebrew/node/$NODE_VERSION/bin/npm $BIN_DIR/npm"
sudo ln -s "$PREF/share/nodebrew/node/$NODE_VERSION/bin/npx $BIN_DIR/npx"
cleaner $CBUILD # Clean up files
echo "Done"
