#!/bin/bash
CGLOBS=/tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing patch..."
cd $CPKG
if [[ "$ARCH" == "i686" ]];then
    installer "https://dl.bintray.com/chromebrew/chromebrew/patch-2.7.5-chromeos-i686.tar.xz" $CPKG/patch.tar.xz
elif [[ "$ARCH" == "x86_64" ]];then 
	installer "https://dl.bintray.com/chromebrew/chromebrew/patch-2.7.5-chromeos-x86_64.tar.xz" $CPKG/patch.tar.xz
fi
unpacker "patch.tar.xz" $CBUILD
sudo cp -r usr/local/ /usr/  # Move all of the files
cleaner $CBUILD # Clean up files
echo "Done"
